# Generated by Django 5.2.17 on 2026-09-28 12:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=5)),
                (
                    "category",
                    models.CharField(
                        choices=[("kyu", "級"), ("dan", "段")], max_length=10
                    ),
                ),
                ("sort_order", models.IntegerField()),
            ],
            options={
                "db_table": "dokoutsu_rank",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("board_sgf", models.TextField()),
                (
                    "turn",
                    models.CharField(
                        choices=[("black", "黒番"), ("white", "白番")], max_length=5
                    ),
                ),
                ("deadline", models.DateTimeField()),
                (
                    "disclosure_type",
                    models.CharField(
                        choices=[
                            ("after_deadline", "締切後に公開URLをシェア"),
                            ("after_answer", "回答後に公開リンクを表示"),
                        ],
                        max_length=20,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dokoutsu_problem",
            },
        ),
        migrations.CreateModel(
            name="AnswerPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=20)),
                ("move", models.TextField()),
                ("body", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_posts",
                        to="dokoutsu.problem",
                    ),
                ),
                (
                    "rank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dokoutsu.rank"
                    ),
                ),
            ],
            options={
                "db_table": "dokoutsu_answerpost",
                "ordering": ["created_at"],
            },
        ),
    ]
