# Generated by Django 5.2.17 on 2026-09-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dokoutsu", "0002_seed_rank"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSendLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("signup", "登録確認"),
                            ("password_reset", "パスワード再発行"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "dokoutsu_emailsendlog",
                "indexes": [
                    models.Index(
                        fields=["email", "purpose", "created_at"],
                        name="dokoutsu_em_email_991685_idx",
                    )
                ],
            },
        ),
    ]
