# Generated by Django 5.2.17 on 2026-09-29 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dokoutsu", "0003_emailsendlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnswerPostLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="dokoutsu.problem",
                    ),
                ),
            ],
            options={
                "db_table": "dokoutsu_answerpostlog",
                "indexes": [
                    models.Index(
                        fields=["ip_address", "problem", "created_at"],
                        name="dokoutsu_an_ip_addr_8a8d97_idx",
                    )
                ],
            },
        ),
    ]
